---
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    create_environment:
      # Need the tags to calculate the version (sometimes).
      - git fetch --tags

      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest

    build:
      html:
        - uvx nox -e docs -- html
